#pragma once


struct SummaryStructure 
{
    double thr;
    double eff;
    double effErr;
    double clSize;
    double clSizeErr;
    double timing;
};

struct GraphData 
{
    TGraphErrors* graphs;
    std::vector<double> x;
    std::vector<double> y;
    std::vector<double> xErr;
    std::vector<double> yErr;
    int num;
};

struct ProcessedSimulation
{
    std::vector<double> thr;
    std::vector<double> thrErr;
    std::vector<double> thrNoErr;
    std::vector<double> eff;
    std::vector<double> effErr;
    std::vector<double> clSize;
    std::vector<double> clSizeErr;
    std::vector<double> timing;
    TTree * tree;
    int num;
};

struct Residuals
{
    std::vector<double> res;
    std::vector<double> resUnc;
};


void Remove_everyNpoints(TGraph* g, int N, int startIndex = 0) 
{

    if (!g) return;
    int n = g->GetN();
    std::vector<double> xNew, yNew;
    xNew.reserve(n);
    yNew.reserve(n);

    for (int i = 0; i < n; ++i) {
        // Keep only points that are not every N-th after offset
        if ((i - startIndex) % N != 0) {
            double x, y;
            g->GetPoint(i, x, y);
            xNew.push_back(x);
            yNew.push_back(y);
        }
    }

    // Replace graph contents
    g->Set(n = xNew.size());
    for (int i = 0; i < n; ++i)
        g->SetPoint(i, xNew[i], yNew[i]);
}

GraphData get_mergedData(std::string branch)
{
    // This method gets the measurement data input from 2 files and merges them into 1 set: low + high gain settings
    TFile *dataInputLowIBIAS = TFile::Open("plotting_scripts/root_input/xybinsIDB100IBIAS05_Clsize_Xbin16_XNsteps1_Xstepsize0_Yfix-1.root");
    TFile *dataInputHighIBIAS = TFile::Open("plotting_scripts/root_input/xybinsIDB120IBIAS43_Clsize_Xbin16_XNsteps1_Xstepsize0_Yfix-1.root");
    if (!dataInputLowIBIAS || dataInputLowIBIAS->IsZombie() || !dataInputHighIBIAS || dataInputHighIBIAS->IsZombie()) {
        std::cerr << "Error: cannot open the input data files." << std::endl;
        return GraphData();
    }

    // Retrieve the data TMultiGraph. Generated by Lucian Fasselt
    TMultiGraph *dataLowIBIAS     = (TMultiGraph*)dataInputLowIBIAS->Get(branch.c_str());
    TMultiGraph *dataHighIBIAS    = (TMultiGraph*)dataInputHighIBIAS->Get(branch.c_str());

    if (!dataLowIBIAS || !dataHighIBIAS) 
    {
        std::cerr << "Error: could not find TMultiGraph for either one of the files." << std::endl;
        return GraphData();
    }


    //Extract the first (and probably only) TGraph from each MultiGraph Object
    TGraph *gLow  = (TGraph*)dataLowIBIAS->GetListOfGraphs()->At(0);  // Low IBIAS high threshold
    TGraph *gHigh = (TGraph*)dataHighIBIAS->GetListOfGraphs()->At(0); // High IBIAS low threshold

    // Remove points for over zealous data takers
    for (int i = 0; i < 3; i++)
    {
        Remove_everyNpoints(gLow, 2, 1);
    }

    // Merge high and low threshold data sets
    TGraphErrors *dataMerged = new TGraphErrors();

    int nMerged = 0;
    // Store and return vectors for further residual computation
    std::vector<double> dataThr, dataBranch, dataThrErr, dataBranchErr;
     // Add points from the low threshold between 200 and 720
    for (int i = 0; i<gHigh->GetN(); i++)
    {
        double x, y;
        gHigh->GetPoint(i, x, y);
        double yErr = gLow->GetErrorY(i);
        if (x >= 200 && x <= 720) 
        {
            std::cout << "y: " << y << "; yErr" << yErr << std::endl;
            dataThr.push_back(x);
            dataThrErr.push_back(x *0.03);
            dataBranch.push_back(y);
            dataBranchErr.push_back(yErr);
            dataMerged->SetPoint(nMerged, x, y);
            dataMerged->SetPointError(nMerged,x *0.03, yErr); 
            nMerged++;
        }        
    }

    // Add points from high threshold for x > 700
    for (int i = 0; i<gLow->GetN(); i++)
    {
        double x, y;
        gLow->GetPoint(i, x, y);
        double yErr = gLow->GetErrorY(i);
        if (x > 900 && x <= 2000) 
        {
            dataThr.push_back(x);
            dataThrErr.push_back(x *0.03);
            dataBranch.push_back(y);
            dataBranchErr.push_back(yErr);
            dataMerged->SetPoint(nMerged, x, y);
            //dataMerged->SetPointError(nMerged,x *0.03, yErr); 
            dataMerged->SetPointError(nMerged,x *0., yErr); 
            nMerged++;
        }        
    }
    GraphData values;
    values.graphs = dataMerged; 
    values.x = dataThr;
    values.y = dataBranch;
    values.xErr = dataThrErr;
    values.yErr = dataBranchErr;
    values.num = nMerged;
    return values;
}

Residuals compute_residuals(TTree *sortedSummary, GraphData values, std::string branch)
{
    // Store values for residuals from simulation.
    std::vector<int> thresholds = {200, 230, 340, 450, 550, 630, 710, 910, 1000, 1100, 1200, 1250, 1350, 1450, 1500, 1600, 1650, 1800, 1850};
    std::vector<double> vSimRes, vErrSimRes;
    int nEntriesSummary = sortedSummary->GetEntries();
    double sThr, sEff, sEffErr, sClSize, sClSizeErr, sTiming;
    sortedSummary->SetBranchAddress("threshold", &sThr);
    sortedSummary->SetBranchAddress("efficiency", &sEff);
    sortedSummary->SetBranchAddress("efficiencyError", &sEffErr);
    sortedSummary->SetBranchAddress("clusterSize", &sClSize);
    sortedSummary->SetBranchAddress("clusterSizeError", &sClSizeErr);
    sortedSummary->SetBranchAddress("timing", &sTiming);
    double lastThr = 0;
    for (int i = 0; i< nEntriesSummary; i++) 
    { 
        sortedSummary->GetEntry(i);
        if (std::find(thresholds.begin(), thresholds.end(), sThr) != thresholds.end() && sEff > 0) 
        {
            if(sThr != lastThr)
            {
                if (branch == "MultiEff")
                {
                    vSimRes.push_back(sEff);
                    vErrSimRes.push_back(sEffErr);
                }
                else
                {
                    vSimRes.push_back(sClSize);
                    vErrSimRes.push_back(sClSizeErr);
                }
            }
            lastThr = sThr;
            
        }
    }
    std::vector<double> dataThr = values.x;
    std::vector<double> dataBranch = values.y;
    std::vector<double> dataErrBranch = values.yErr;

    // Compute data vs sim residuals
    std::vector<double> residuals, uncResiduals;
    for (int i = 0; i< dataThr.size(); i++)
    {
        double data = dataBranch[i];
        double sim = vSimRes[i];
        double sigD = dataErrBranch[i];
        double sigS = vErrSimRes[i];

        double r = (data - sim) / sim * 100;
        //double r = data - sim;
        //double sigR = std::sqrt( std::pow(sigD / sim, 2) + std::pow(((data - sim) * sigS) / std::pow(sim, 2), 2));
        double sigR = std::sqrt (std::pow(sigD, 2) + std::pow(sigS,2)) * 100;
        
        residuals.push_back(r);
        uncResiduals.push_back(sigR);
    }
    Residuals residualValues;
    residualValues.res    = residuals;
    residualValues.resUnc = uncResiduals;
    return residualValues;
}

ProcessedSimulation sort_simTree(int runNumber, std::string tag)
{
    // Build file path
    std::string summaryPath = Form("Plots/local_%04d/%s/summary.root", runNumber, tag.c_str());
    std::cout << "Opening: " << summaryPath << std::endl;

    TFile *summaryFile = TFile::Open(summaryPath.c_str(), "READ");
    if (!summaryFile || summaryFile->IsZombie()) {
        std::cerr << "Could not open file: " << summaryPath << std::endl;
        return ProcessedSimulation();
    }

    TTree *summaryTree = (TTree*) summaryFile->Get("summaryTree");
    if (!summaryTree) {
        std::cerr << "No summaryTree in file: " << summaryPath << std::endl;
        return ProcessedSimulation();
    }

    double threshold, efficiency, effError, timing, clSize, clSizeError;
    summaryTree->SetBranchAddress("threshold", &threshold);
    summaryTree->SetBranchAddress("efficiency", &efficiency);
    summaryTree->SetBranchAddress("effError", &effError);
    summaryTree->SetBranchAddress("clSize", &clSize);
    summaryTree->SetBranchAddress("clSizeError", &clSizeError);
    summaryTree->SetBranchAddress("timing", &timing);


    // First we need to sort the tree, because not all runs are performed in consecutive threshold values
    int nEntriesSummary = summaryTree->GetEntries();

    std::vector<SummaryStructure> summaryToSort;
    for (Long64_t i = 0; i < nEntriesSummary; i++) 
    {
        summaryTree->GetEntry(i);
        SummaryStructure sS;
        sS.thr = threshold;
        sS.eff = efficiency;
        sS.effErr = effError;
        sS.clSize = clSize;
        sS.clSizeErr = clSizeError;
        sS.timing = timing;
        summaryToSort.push_back(sS);
    }

    // sort by threshold
    std::sort(summaryToSort.begin(), summaryToSort.end(),
        [](const SummaryStructure &a, const SummaryStructure &b) {
            return a.thr < b.thr;
        });
    // Save sorted tracks to a new tree
    TTree *sortedSummary = new TTree("SortedSummary", "Time-sorted summary");

    double sThr, sEff, sEffErr, sClSize, sClSizeErr, sTiming;
    sortedSummary->Branch("threshold", &sThr, "threshold/D");
    sortedSummary->Branch("efficiency", &sEff, "efficiency/D");
    sortedSummary->Branch("efficiencyError", &sEffErr, "efficiencyError/D");
    sortedSummary->Branch("clusterSize", &sClSize, "clusterSize/D");
    sortedSummary->Branch("clusterSizeError", &sClSizeErr, "clusterSizeError/D");
    sortedSummary->Branch("timing", &sTiming, "timing/D");

    for (auto &sS : summaryToSort) {
        sThr = sS.thr;
        sEff = sS.eff;
        sEffErr = sS.effErr;
        sClSize = sS.clSize;
        sClSizeErr = sS.clSizeErr;
        sTiming = sS.timing;
        sortedSummary->Fill();
    }
    // Finished sorting the summary entries

    std::vector<double> vThr, vThrErr, vThrNoErr, vEff, vEffErr, vClSize, vClSizeErr, vTiming;
    vThr.reserve(nEntriesSummary);
    vThrErr.reserve(nEntriesSummary);
    vEff.reserve(nEntriesSummary);
    vThrNoErr.reserve(nEntriesSummary);
    vEffErr.reserve(nEntriesSummary);
    vClSize.reserve(nEntriesSummary);
    vClSizeErr.reserve(nEntriesSummary);
    vTiming.reserve(nEntriesSummary);
    int numValidEntries = 0;
    double lastThr = 0;
    for (int i = 0; i< nEntriesSummary; i++) 
    { 
        sortedSummary->GetEntry(i);
        //std::cout << "Threshold: " << sThr << " Efficiency: " << sEff <<std::endl;
        if ( (sThr == 150 || int(sThr) %100 == 0 ) && sThr < 2000 && sEff > 0)
        {
            vThr.push_back(sThr);
            vThrNoErr.push_back(0);
            vThrErr.push_back(sThr * 0.03); // 3% quoted from calibration paper
            vEff.push_back(sEff);
            vEffErr.push_back(sEffErr);
            vClSize.push_back(sClSize);
            vClSizeErr.push_back(sClSizeErr);
            vTiming.push_back(sTiming);
            numValidEntries++;
        }
    }

    ProcessedSimulation simValues;
    simValues.thr = vThr;
    simValues.thrErr = vThrErr;
    simValues.thrNoErr = vThrNoErr;
    simValues.eff = vEff;
    simValues.effErr = vEffErr;
    simValues.clSize = vClSize;
    simValues.clSizeErr = vClSizeErr;
    simValues.timing = vTiming;
    simValues.tree = sortedSummary;
    simValues.num = numValidEntries;
    return simValues;
}

ProcessedSimulation sort_simTree_Digital(int runNumber, std::string tag)
{
    // Build file path
    std::string summaryPath = Form("Plots/local_%04d/%s/summary.root", runNumber, tag.c_str());
    std::cout << "Opening: " << summaryPath << std::endl;

    TFile *summaryFile = TFile::Open(summaryPath.c_str(), "READ");
    if (!summaryFile || summaryFile->IsZombie()) {
        std::cerr << "Could not open file: " << summaryPath << std::endl;
        return ProcessedSimulation();
    }

    TTree *summaryTree = (TTree*) summaryFile->Get("summaryTree");
    if (!summaryTree) {
        std::cerr << "No summaryTree in file: " << summaryPath << std::endl;
        return ProcessedSimulation();
    }

    double threshold, efficiency, effError, timing, clSize, clSizeError;
    summaryTree->SetBranchAddress("threshold", &threshold);
    summaryTree->SetBranchAddress("efficiency", &efficiency);
    summaryTree->SetBranchAddress("effError", &effError);
    summaryTree->SetBranchAddress("clSize", &clSize);
    summaryTree->SetBranchAddress("clSizeError", &clSizeError);
    summaryTree->SetBranchAddress("timing", &timing);


    // First we need to sort the tree, because not all runs are performed in consecutive threshold values
    int nEntriesSummary = summaryTree->GetEntries();

    std::vector<SummaryStructure> summaryToSort;
    for (Long64_t i = 0; i < nEntriesSummary; i++) 
    {
        summaryTree->GetEntry(i);
        SummaryStructure sS;
        sS.thr = threshold;
        sS.eff = efficiency;
        sS.effErr = effError;
        sS.clSize = clSize;
        sS.clSizeErr = clSizeError;
        sS.timing = timing;
        summaryToSort.push_back(sS);
    }

    // sort by threshold
    std::sort(summaryToSort.begin(), summaryToSort.end(),
        [](const SummaryStructure &a, const SummaryStructure &b) {
            return a.thr < b.thr;
        });
    // Save sorted tracks to a new tree
    TTree *sortedSummary = new TTree("SortedSummary", "Time-sorted summary");

    double sThr, sEff, sEffErr, sClSize, sClSizeErr, sTiming;
    sortedSummary->Branch("threshold", &sThr, "threshold/D");
    sortedSummary->Branch("efficiency", &sEff, "efficiency/D");
    sortedSummary->Branch("efficiencyError", &sEffErr, "efficiencyError/D");
    sortedSummary->Branch("clusterSize", &sClSize, "clusterSize/D");
    sortedSummary->Branch("clusterSizeError", &sClSizeErr, "clusterSizeError/D");
    sortedSummary->Branch("timing", &sTiming, "timing/D");

    for (auto &sS : summaryToSort) {
        sThr = sS.thr;
        sEff = sS.eff;
        sEffErr = sS.effErr;
        sClSize = sS.clSize;
        sClSizeErr = sS.clSizeErr;
        sTiming = sS.timing;
        sortedSummary->Fill();
    }
    // Finished sorting the summary entries

    std::vector<double> vThr, vThrErr, vThrNoErr, vEff, vEffErr, vClSize, vClSizeErr, vTiming;
    vThr.reserve(nEntriesSummary);
    vThrErr.reserve(nEntriesSummary);
    vEff.reserve(nEntriesSummary);
    vThrNoErr.reserve(nEntriesSummary);
    vEffErr.reserve(nEntriesSummary);
    vClSize.reserve(nEntriesSummary);
    vClSizeErr.reserve(nEntriesSummary);
    vTiming.reserve(nEntriesSummary);
    int numValidEntries = 0;
    double lastThr = 0;
    for (int i = 0; i< nEntriesSummary; i++) 
    { 
        sortedSummary->GetEntry(i);
        //std::cout << "Threshold: " << sThr << " Efficiency: " << sEff <<std::endl;
        if ( true)
        {
            vThr.push_back(sThr);
            vThrNoErr.push_back(0);
            vThrErr.push_back(sThr * 0.03); // 3% quoted from calibration paper
            vEff.push_back(sEff);
            vEffErr.push_back(sEffErr);
            vClSize.push_back(sClSize);
            vClSizeErr.push_back(sClSizeErr);
            vTiming.push_back(sTiming);
            numValidEntries++;
        }
    }

    ProcessedSimulation simValues;
    simValues.thr = vThr;
    simValues.thrErr = vThrErr;
    simValues.thrNoErr = vThrNoErr;
    simValues.eff = vEff;
    simValues.effErr = vEffErr;
    simValues.clSize = vClSize;
    simValues.clSizeErr = vClSizeErr;
    simValues.timing = vTiming;
    simValues.tree = sortedSummary;
    simValues.num = numValidEntries;
    return simValues;
}